### ISSUE TITLE
No css/site.min.css generated after Gulp build

### ISSUE THREAD

**Issue by paulbrislane** [alistairtweedie/pintsize#7]
...runs fine otherwise

**Comment by alistairtweedie** [comment]
What OS are you on? Are you able to provide a step by step process? - I've tried replicating this but no luck so far.

**Comment by paulbrislane** [comment]
unfortunately at work on a Win7 machine...

...the npm install falls down at the node-sass@0.9.6 install 'node build.js'

I can install node-sass separately which allows Gulp to run but the css/site.min.css isn't subsequently generated.

**Comment by alistairtweedie** [comment]
It seems that node-sass is causing problems in Windows. It also seems this module is actually not required for the project. Gulp-sass takes care of all the pre processing without the need for node-sass. If you remove node-sass from your package.json file, delete all node modules and re run npm install let me know if you have any issues. If all is ok I'll update the project.

**Comment by paulbrislane** [comment]
Yes, all fine now.

Thanks

**Comment by alistairtweedie** [comment]
This is now fixed. Thanks
